---
title: "Saltmarsh Evolution"
---

Saltmarshes are key ecosystems that inhabit low-energy temperate intertidal areas. Provide a wide set of ecosystem services such 
as coastal protection, carbon sequestration and food provisioning, among others. Unfortunately, like most of coastal and marine 
ecosystems, these valuable systems face multiple threads that threaten their survival capacity. Two of the major threads that 
threaten survival capacity of saltmarshes are sea level rise and reduced sediment availability.

[Egidazu-de la Parte *et al.*, 2025](https://www.sciencedirect.com/science/article/pii/S0048969724083220?via%3Dihub) explored the 
future distributions of three saltmarshes under varied sea  level rise and sediment availability scenarios. In this tab, you can 
explore and download the results described by [Egidazu-de la Parte *et al.* (2025)](https://www.sciencedirect.com/science/article/pii/S0048969724083220?via%3Dihub) 
under the sea level rise scenarios and the actual sediment availability scenario used in the study. You can also download the complete results and the trained models [here](https://github.com/begidazu/MESIT/tree/main/results/saltmarshes).

## How to navigate saltmarsh evolution?

1. Select the Study Area from the dropdown.
2. Select the prediction year you want to explore (the first year of the list is the baseline, so it has the same results for all sea level rise scenarios).
3. Choose the sea level rise scenario that you want to display in the map from the radio buttons that appear below the dropdown (be patient, it can take a little bit of time).
4. Explore the habitat distribution changes for the sea level rise scenarios from the selected study area and year in the tables. Also explore aggregated yearly accretion rates for saltmarsh and mudflat habitats.
5. Download the results, if needed, with the 'Download' button or get additional information with the 'Info' button.
6. Reset the results to restart the configuration.

## How to interpret the results?

Results should be interpreted as potential habitat distributions and extents under the assumptions and limitations in 
[Egidazu-de la Parte *et al.* (2025)](https://www.sciencedirect.com/science/article/pii/S0048969724083220?via%3Dihub). Uncertainties 
of sea level rise projections, as well as model uncertainties from model simplifications, assumptions and data limitations, could 
be high. Thus, future projections of the habitat distributions should never be taken as absolute and precise distributions for the 
selected year and sea level rise scenario. However, results could be used to take management decisions based on the trends of 
habitat changes presented by the different scenarios, recommending the use of a precautionary aproach. 

With regards to habitat extent results, we recommend to compare habitat increases and decreases in relative terms to baseline 
results. According to accretion rates, results represent the yearly aggregated accretion by saltmarsh and mudflat habitats. 
Accretion is the major process that make saltmarshes one of the most important ecosystems in the world sequestering carbon, and 
combined with sediment carbon content and bulk density can be used to measure sequestered carbon by these habitats in each scenario.

For detailed information of the applied model, scenarios and results, please read [Egidazu-de la Parte *et al.* (2025)](https://www.sciencedirect.com/science/article/pii/S0048969724083220?via%3Dihub).
